apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: test-static-ip
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: test-cert
    hosts:
    - test.{{ .Values.domain }}
  rules:
  - host: test.{{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: test-service
          servicePort: 80
